// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaPmY99o-Tf7_WHeOYJP-tWg3VcImhizw',
    appId: '1:1037982520750:web:ef549517e090543734e43f',
    messagingSenderId: '1037982520750',
    projectId: 'final-project-28991',
    authDomain: 'final-project-28991.firebaseapp.com',
    databaseURL: 'https://final-project-28991-default-rtdb.firebaseio.com',
    storageBucket: 'final-project-28991.appspot.com',
    measurementId: 'G-KMC08EN685',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyLBz6uno_2Km6QfwwZ-pXnNQsw2zP7UA',
    appId: '1:1037982520750:android:a985336aad084b0134e43f',
    messagingSenderId: '1037982520750',
    projectId: 'final-project-28991',
    databaseURL: 'https://final-project-28991-default-rtdb.firebaseio.com',
    storageBucket: 'final-project-28991.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl3OfBA-IHUo43vxz3MPJ4c7h7EdU5tB8',
    appId: '1:1037982520750:ios:38ba70b4cc7d794234e43f',
    messagingSenderId: '1037982520750',
    projectId: 'final-project-28991',
    databaseURL: 'https://final-project-28991-default-rtdb.firebaseio.com',
    storageBucket: 'final-project-28991.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl3OfBA-IHUo43vxz3MPJ4c7h7EdU5tB8',
    appId: '1:1037982520750:ios:75b57309f3c4dc2834e43f',
    messagingSenderId: '1037982520750',
    projectId: 'final-project-28991',
    databaseURL: 'https://final-project-28991-default-rtdb.firebaseio.com',
    storageBucket: 'final-project-28991.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
